wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1650205957
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      - 11
      4: 3.9.5
      5: 0.12.9
      8:
      - 5
